GET http://localhost:3001/api/users/get_users

###

GET http://localhost:3001/api/users/get_user?username=adminjwt2

###

POST http://localhost:3001/api/auth/login
Content-Type: application/json

{
    "username": "adminjwt",
    "password": "1234"
}

###

DELETE http://localhost:3001/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluand0IiwiaWF0IjoxNjc4NTQyMjkyfQ.Lnh5vXgsGdVj-T2NxxQikw6YNKqHZ32IDCjDk4juRwA"
}

###

GET http://localhost:3001/api/users/login?username=admin&password=1234

###

DELETE http://localhost:3001/api/users/delete_user?username=admin


###

POST http://localhost:3001/api/subjects/get_filtered_subjects?year=4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjc5NjUzOTIzLCJleHAiOjE2Nzk2NTc1MjN9.AvBoGpRR3_2eHqCrZdqlfH1BEpIkH5aT2ysQWwYJNFI

{
    "activeFilters": []
}

###

GET http://localhost:3001/api/subjects/get_subject?subject_code=TIT404
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNjc5NjUzOTIzLCJleHAiOjE2Nzk2NTc1MjN9.AvBoGpRR3_2eHqCrZdqlfH1BEpIkH5aT2ysQWwYJNFI

###

POST http://localhost:3001/api/subjects/add_subject
Content-Type: application/json

{
    "subject_code": "TIT404",
    "name": "Computer Graphics & Animations",
    "description": "Computer graphics deals with generating images and art with the aid of computers.",
    "year": 4,
    "branch": "Information Technology",
    "credits": 3,
    "tags": [],
    "professors": [{
        "name": "Shikha Goswami",
        "year": 2022
    }]
}

###

###

DELETE http://localhost:3001/api/subjects/delete_subject/tit576

###

PATCH http://localhost:3001/api/subjects/rate_difficulty
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzaHV0b3NoNDRrcyIsImlhdCI6MTY3ODY0Njk3NywiZXhwIjoxNjc4NjUwNTc3fQ.IcCZW5QLKTQqOsvCbE9mDHPE1pMACyjG9q-wNDxLyzw

{
    "subjectCode": "TIT404",
    "userDifficulty": 1
}

###

GET http://localhost:3001/api/subjects/get_subjects
Content-Type: application/json


###

GET http://localhost:3001/api/subjects/get_dir_files?subject_code=TIT486&prefix=qp
Content-Type: application/json
